export const GET_ENTERPRISE =
  'select ENTERPRISE_ID, ENTERPRISE_NAME from UAN_DWH_STG.arg_cfg_enterprise_stg where deleted is null and client_id = 9999';

export const INSERT_ENTERPRISE =
  "INSERT INTO UAN_DWH_CNF.UAN_APP_TENANT_USER_MAPPING (CLIENT_ID, CLIENT_NAME, USER_ID, USER_NAME, TENANT_ID) values('${clientID}', '${clientName}', '${userId}', '${userName}', '${enterpriseId'})";

export const REMOVE_ENTERPRISE =
  "DELETE FROM UAN_DWH_CNF.UAN_APP_TENANT_USER_MAPPING WHERE USER_ID='${userId}' AND CLIENT_ID='${clientID}' AND TENANT_ID=${enterpriseId}";

export const CASE_COUNT_BY_REPORT_QUERY =
  'SELECT UCI.CLIENT_ID, UCI.ENTERPRISE_ID, UCI.CASE_REPORT_TYPE, COUNT(DISTINCT UCI.CASE_ID) FROM UAN_DWH_EDW.UAN_CASE_INFO UCI WHERE UCI.CASE_DELETED IS NULL AND UCI.CASE_STATE_ID <> 1 AND  UCI.ENTERPRISE_ID = ${enterpriseId} GROUP BY UCI.CLIENT_ID, UCI.ENTERPRISE_ID, UCI.CASE_REPORT_TYPE;';
